services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"
  firefox:
    image: selenium/node-firefox
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
  chrome:
    image: selenium/node-chrome
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
